### ISSUE TITLE
Traceback issue

### ISSUE THREAD

**Issue by axsddlr** [picklejason/ValorantRankedPointsBot#2]
bot launch issue:
```Traceback (most recent call last):
  File "bot.py", line 141, in send_update
    users = json.load(f)
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Unhandled exception in internal background task 'relog'.
Traceback (most recent call last):
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "bot.py", line 31, in relog
    _, headers = await rs.run(USERNAME, PASSWORD)
  File "E:\Programs\gitrepos\ValorantRankedPointsBot\RSO_AuthFlow.py", line 29, in run
    data = pattern.findall(data['response']['parameters']['uri'])[0]
KeyError: 'response'
```

**Comment by picklejason** [comment]
Double check your login info in your .env file.

**Comment by axsddlr** [comment]
> Double check your login info in your .env file.

its correct

**Comment by picklejason** [comment]
I'm not sure what exactly the problem is then. It's getting a bad response from the request, only the account in the .env is used to send the request. Someone else had a similar problem and just hard coded their login for USERNAME and PASSWORD in bot.py instead of getting it from .env

**Comment by axsddlr** [comment]
that sucks then, hard coding login isnt good

**Comment by axsddlr** [comment]
also -link command gives me: 

Best thing for me is keeping login in info.json file
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Ruhkloos\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by picklejason** [comment]
I think I may have found the problem. The error is showing because there is nothing in the json. I uploaded the json completely blank. Putting { } instead of making it completely blank seems to fix it. Let me test a few more things, don't have that much experience with json files so I apologize.

**Comment by picklejason** [comment]
@Rehkloos After some debugging, I figured out the cause of the errors. I'm assuming you're running this on Windows. Apparently `os.getenv('USERNAME')` returns your Windows username rather than what is in the .env. To fix this just change the variable USERNAME in .env to something else like USER_NAME. Then in bot.py just change it to `os.getenv('USER_NAME')`.

**Comment by axsddlr** [comment]
lol makes sense, i was going to run this on my vps after i get it working since i dont work in linux exclusively

**Comment by axsddlr** [comment]
also having an issue with embeds sending twice 

![image](https://user-images.githubusercontent.com/1954355/104078077-46fb3f00-51ea-11eb-95de-cb35540848d4.png)

**Comment by picklejason** [comment]
I can't seem to reproduce the duplicate embed, I think you may have an instance of the bot you didn't close when testing. See if any other commands repeat themselves.

**Comment by axsddlr** [comment]
nope only one instance. Is there a way to run a check in code to only send it once?

**Comment by picklejason** [comment]
Is it duplicating each time you do -profile?

**Comment by axsddlr** [comment]
correct

**Comment by picklejason** [comment]
Try and regenerate a new discord token and reset the bot. If after that it still duplicates then I'll check it out further. I am pretty sure it's only on your side, don't see anything in the code that is making it send twice.

**Comment by axsddlr** [comment]
found the issue, again with windows. its running two instances of python. All solved now;. thansk again

**Comment by axsddlr** [comment]
also wondering why icons from resources.py movements section is not posting the icons

**Comment by picklejason** [comment]
I forgot to mention that those are custom icons. You will have to upload your own in any server the bot is in to access them. You will also have to replace the map in resources as they have unique ids. There should be plenty of tutorials to show you how to use custom emotes for bots. But if it's too much work your can just remove the arrows.
